{
  "headers": {
    "username": "hdfhhf",
    "password": "hdhdhd",
    "content-type": "application/json",
    "user-agent": "PostmanRuntime/7.32.3",
    "accept": "*/*",
    "cache-control": "no-cache",
    "postman-token": "0d5d8ce7-e3b3-42e1-a64c-705f94045924",
    "host": "localhost:8081",
    "accept-encoding": "gzip, deflate, br",
    "connection": "keep-alive",
    "content-length": "100"
  },
  "clientCertificate": null,
  "method": "POST",
  "scheme": "http",
  "queryParams": {},
  "requestUri": "/api/customer",
  "queryString": "",
  "version": "HTTP/1.1",
  "maskedRequestPath": "/customer",
  "listenerPath": "/api/*",
  "relativePath": "/api/customer",
  "localAddress": "/127.0.0.1:8081",
  "uriParams": {},
  "rawRequestUri": "/api/customer",
  "rawRequestPath": "/api/customer",
  "remoteAddress": "/127.0.0.1:58573",
  "requestPath": "/api/customer"
}